Kapitel 33/Django-Aufgabe/lightning/ideas/urls.py
#.../ideas/urls.py
from django.urls import path
from . import views

app_name = 'ideas'

urlpatterns = [
    path(route='',view=views.index, name='index'),
    path(route='question/<int:question_id>/',
         view=views.question_index, 
         name='question_index'),
    path(route='save_new_idea/<int:question_id>/',
         view=views.save_new_idea,
         name='save_new_idea'),
    path(route='new/',
         view=views.new_question, name='new_question'),
    path(route='new_question_response',
         view=views.save_new_question,
         name='save_new_question'),
    path(route='search/',
         view=views.search, name='search')

]


Kapitel 33/Django-Aufgabe/lightning/lightning/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ideas/', include('ideas.urls')),     #1
    path('admin/', admin.site.urls),
]

Kapitel 33/Django-Aufgabe/lightning/ideas/models.py
#.../ideas/models.py
from django.db import models
HELP_KEYWORD=''' Das Schlüsselwort sollte ein sinnloses, 
aber gut aussprechbares Wort sein 
(z.B. "magoba" oder "baluto").'''                                       
HELP_END='''Zeitpunkt, zu dem die Frage gelöscht werden soll'''                                               #1
class Question(models.Model):
    text = models.CharField(max_length=100,
          verbose_name='Frage')                       #2
    author = models.CharField(max_length=20,
                       verbose_name='Name') 
    end =  models.DateTimeField(
           verbose_name='Löschzeit',
           help_text=HELP_END)                        #3
    lifespan_ideas = models.DurationField(
        verbose_name='Lebensdauer einer Idee')
    def __str__(self):
        return '{} fragt: {}'.format(self.author,
                                     self.text)

class Idea(models.Model):
    text = models.CharField(max_length=200,
             verbose_name='Idee')
    end =  models.DateTimeField()
    question = models.ForeignKey(Question,
                          on_delete=models.CASCADE)
    def __str__(self):
        return self.text

class Keyword(models.Model):
    text = models.CharField(max_length=20,
                           verbose_name='Schlüsselwort',
                            help_text=HELP_KEYWORD)



Kapitel 33/Django-Aufgabe/lightning/ideas/views.py
#.../ideas/views.py

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta

from .models import Question, Idea, Keyword


def index(request):
    question_list = Question.objects.all()            #1
    context ={ 'question_list':question_list }        #2
    return render(request, 'ideas/index.html', context)


def question_index(request, question_id):
    question = get_object_or_404(Question,
                                 pk=question_id)     #1
    idea_list = question.idea_set.all()              #2
    context = { 'question': question,
                'idea_list': idea_list}              #3
    return render(request, 
                 'ideas/question_index.html', context)


def new_question(request):
    context = { 'lifespan_choices': [1, 3, 7]}        #1
    return render(request, 'ideas/new_question.html', context)


def save_new_question (request):
    text = request.POST['text']                       #1                 
    keyword = request.POST['keyword']
    author = request.POST['author']
    lifespan_ideas = int(request.POST['lifespan_ideas'])
    try:                                              #2
        lifespan = int(request.POST['choice'])
    except:
        lifespan = 1
    valid_keywords = [k.text for k in Keyword.objects.all()] 
    if keyword not in valid_keywords:                 #3
        message='Das Schlüsselwort ist ungültig.'
    elif len(text) < 5:                               
        message='Bitte eine längere Frage eingeben.'
    elif len(author) < 3:
        message='Bitte einen längeren Namen eingeben.'
    else:
        message = ''
    if message:                                       #4
        context = {'message': message,
                   'lifespan_choices': [1, 3, 7],
                   'question_text':text}
        return render(request, 
                     'ideas/new_question.html',
                     context)                         #5
    else:                                             #6
        end = timezone.now() + timedelta(days=lifespan)
        q = Question(text=text, author=author, end=end,
              lifespan_ideas=timedelta(hours=lifespan_ideas))
        q.save()
        return HttpResponseRedirect(reverse('ideas:index'))          #7


def save_new_idea(request, question_id):
    question = get_object_or_404(Question, 
                                 pk=question_id)      #1
    text = request.POST['text']                       #2
    if len(text) < 10:                                #3
        message = 'Der Text ist zu kurz! (Min. 10 Zeichen)'
    else:
        message = ''
        end = timezone.now() + question.lifespan_ideas
        idea = Idea(text=text,
                    question=question,
                    end=end)                          #4
        idea.save()
    context = {'question': question,
               'message': message,'idea_text':text,
               'idea_list': question.idea_set.all()}  #5
    return render(request, 
                  'ideas/question_index.html',
                  context)                            #6


def search(request):
    text = request.POST['text']
    if len(text) < 3:                                 #1
        message = 'Der Suchbegriff ist zu kurz!'
        context = {'message': message}                #2
    else:
        results = [(idea, idea.question)
                       for idea in Idea.objects.all()
                       if text in idea.text]          #3
        context = {'results': results}                #4
    return render(request,
                  'ideas/search_results.html',
                  context)                            

Kapitel 33/Django-Aufgabe/lightning/ideas/templates/ideas/index.html
<h1> Ideenspeicher</h1>
{% if question_list %}
  <ul>
  {% for question in question_list %}
    <li><a href="{% url 'ideas:question_index' question.id %}">
      {{ question.text }}</a> <br/>
      <i> bis {{ question.end }}</i>
    </li>
  {% endfor %}
  </ul>
{% else %}
  <p>Noch keine Fragen.</p>
{% endif %}
<p><a href="{% url 'ideas:new_question' %}">Neue Frage</a></p>

<form action="{% url 'ideas:search' %}" method="post">  {% csrf_token %} 
  <p>Suchbegriff:  <input type="text" size=20 name="text" />
     <input type="submit" value="Suchen"/>
  </p>
</form>


Kapitel 33/Django-Aufgabe/lightning/ideas/templates/ideas/new_question.html
<h1>Neue Frage</h1>
{% if message %}                      
  <p><strong>{{ message }}</strong></p>
{% endif %}

<form action="{% url 'ideas:save_new_question' %}" method="post">
  {% csrf_token %}
  <p>Schlüsselwort:  
    <input type ="password" size=20 name="keyword" />
  </p>
  <p>Frage: <input type ="text" size=80 name="text"
    value="{{ question_text }}" /> </p>
  <p>Name (Pseudonym): 
  <input type="text" size= 20 name="author" /> </p>
  <p>Lebensdauer der Frage:<br/>
  {% for days in lifespan_choices %}
   <input type="radio" name="lifespan" value="{{ days }}">
   {{ days }} {% if days == 1 %}Tag {% else %}Tage{% endif %} 
  <br/>
  {% endfor %} </p>
  <p>Lebensdauer einer Idee:<br/>
   <input type="radio" name="lifespan_ideas" value="1" checked="checked" />
   1 Stunde </br>
    <input type="radio" name="lifespan_ideas" value="6"/>
   6 Stunden </br> 
  <input type="submit" value="Frage speichern">
  </p> 
</form>
<p><a href="{% url 'ideas:index' %}">
Zurück zur Startseite</a></p>



Kapitel 33/Django-Aufgabe/lightning/ideas/templates/ideas/question_index.html
<h1> Ideen gesucht!</h1>
{{ question.author }} fragt: 
<h3>{{ question.text }}</h3> 
  <ul>
  {% for idea in idea_list %}
    <li>{{ idea.text }}</i>
    </li>
  {% endfor %}
  </ul>

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
<form action="{% url 'ideas:save_new_idea' question.id %}" method="post">
  {% csrf_token %} 
  <p>Neue Idee:   <input type ="text" size= 60 name="text"
    {% if idea_text %}value="{{ idea_text }}"{% endif %}/>
  </p>
  <input type="submit" value="Idee senden">
</form>


<p><a href="{%url 'ideas:index' %}">Zurück zur Startseite</a></p> 



Kapitel 33/Django-Aufgabe/lightning/ideas/templates/ideas/search_results.html
<h1>Suchergebnisse</h1>
{% if message %}<p><strong>{{ message }}</strong></p>
{% else %}
  {% for idea, question in results %}
  <p>
    Idee: <i>{{ idea.text }}</i> (zur Frage <i>{{ question.text }}</i>)
  </p>
  {% endfor %}
{% endif %}

<p><a href="{% url 'ideas:index' %}">Zurück zur Startseite</a></p>
